#!/bin/bash
#
# btr-backup: backup script on btrfs
#
# Usage: btr-backup <target_dir> [rsync-options]
#
# (C) 2010 Tatsuki Sugiura <sugi@nemui.org>, All rights reserved.
# This is free software with ABSOLUTELY NO WARRANTY.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#

set -e

backup_base=/backup
logdir=/var/log/btr-backup

if [ -f /etc/btr-backup.conf ]; then
  . /etc/btr-backup.conf
fi

target="${1%/}"
shift

if [ -z "${target}" ]; then
  echo "Usage: $0 <target_dir> [rsync-options]" >&2
  exit 255
fi

if (echo "${target}" | egrep -q "^[0-9a-zA-Z.-]+:"); then
  host=${target%:*}
  dest="${target#*:}"
else
  host=$(hostname)
  dest="${target}"
fi
dest="${dest////_}"
if [ -z "$dest" ]; then
  dest="ROOT"
fi
logfile="${logdir}/${host}-${dest#_}.log"
dest="${backup_base}/${host}/${dest#_}"

function logstamp {
  echo -n "`date '+%Y/%m/%d %H:%M:%S'` " >> $logfile
}
function logmsg {
  echo "`date '+%Y/%m/%d %H:%M:%S'` $@" >> $logfile
}

if [ -d $logdir ]; then
  mkdir -p "${logdir}"
  chmod 750 $logdir
fi

logmsg "Backup start: ${target}/ -> ${dest}/"

if [ ! -d "${dest}" ]; then
  logmsg "Create destdir '${dest}'"
  mkdir -p "${dest}"
fi

if [ ! -d "${dest}/cur" ]; then
  logstamp
  btrfs subvolume create "${dest}/cur" >> $logfile
fi

logmsg "Run rsync with: -acSHXA --numeric-ids --del --log-file=${logfile} $@ ${target}/ ${dest}/cur/"
rsync -acSHXA --numeric-ids --del --log-file=${logfile} \
	"$@" "${target}/" "${dest}/cur/"

logstamp
btrfs filesystem sync "${dest}/cur" >> $logfile

logstamp
btrfs subvolume snapshot "${dest}/cur" "${dest}/$(date +%Y-%m-%dT%H:%M:%S)" >> $logfile
