#!/bin/bash
#
# btr-backup: backup script on btrfs
#
# Usage: btr-backup [-c config_file] <target_dir> [rsync-options]
#
# (C) 2010 Tatsuki Sugiura <sugi@nemui.org>, All rights reserved.
# This is free software with ABSOLUTELY NO WARRANTY.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#

set -e

backup_base=/backup
logdir=/var/log/btr-backup
default_rsync_opts="-acSHXA --numeric-ids --del"
config_file=/etc/btr-backup.conf
load_config_force=f

getopts c: copt
if [ "$copt" = "c" ]; then
  if [ -z "$OPTARG" ]; then
    echo "No config file path is specified with -c option." >&2
    exit 255
  fi
  config_file="$OPTARG"
  load_config_force=t
  shift $((OPTIND-1))
fi

if [ -f "$config_file" -o $load_config_force = t ]; then
  . "$config_file"
fi

target="${1%/}"
shift

if [ -z "${target}" ]; then
  echo "Usage: $0 [-c config_file] <target_dir> [rsync-options]" >&2
  exit 255
fi

if [ "${target:0:8}" = "rsync://" ]; then
  host="${target:8}"
  host="${host%%/*}"
  dest="${target:8}"
  dest="/${dest#*/}"
elif (echo "${target}" | egrep -q "^[0-9a-zA-Z.-]+:"); then
  host=${target%%:*}
  dest="${target#*:}"
else
  host=$(hostname)
  dest="${target}"
fi
dest="${dest////_}"
if [ -z "$dest" ]; then
  dest="ROOT"
fi
logfile="${logdir}/${host}-${dest#_}.log"
dest="${backup_base}/${host}/${dest#_}"

function logstamp {
  echo -n "`date '+%Y/%m/%d %H:%M:%S'` " >> "$logfile"
}
function logmsg {
  echo "`date '+%Y/%m/%d %H:%M:%S'` $@" >> "$logfile"
}

if [ -d $logdir ]; then
  mkdir -p "${logdir}"
  chmod 750 $logdir
fi

logmsg "Backup start: ${target}/ -> ${dest}/"

if [ ! -d "${dest}" ]; then
  logmsg "Create destdir '${dest}'"
  mkdir -p "${dest}"
fi

if [ ! -d "${dest}/cur" ]; then
  logstamp
  btrfs subvolume create "${dest}/cur" >> "$logfile"
fi

logmsg "Run rsync with: ${default_rsync_opts} --log-file=${logfile} $@ ${target}/ ${dest}/cur/"
rsync ${default_rsync_opts} --log-file=${logfile} "$@" "${target}/" "${dest}/cur/" || true

logstamp
btrfs filesystem sync "${dest}/cur" >> "$logfile"

logstamp
btrfs subvolume snapshot "${dest}/cur" "${dest}/$(date +%Y-%m-%dT%H:%M:%S)" >> "$logfile"
